version: 2
enable-beta-ecosystems: true
 
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
 
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      timezone: "Europe/London"
 
  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      timezone: "Europe/London"
 
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      timezone: "Europe/London"
