name: gaia-live

services:
  # Replace placeholder service name
  gaia:
    build:
      context: .
      # This docker compose file is used in production
      target: live
      dockerfile: Dockerfile
    # Replace placeholder service name
    image: gaia-live
    # Replace placeholder service name
    container_name: gaia-live
    ports:
      - '5000:8080'
