services:
  gaia:
    build:
      context: ..
      dockerfile: Dockerfile
      # Overwrite the main file to use dev stage
      target: dev
    image: gaia:latest
    # Prevent the container from exiting after initialisation
    command: sleep infinity
    init: true
    volumes:
      # Source directory mount
      - ..:/workspaces/gaia:cached

      # Allow the devcontainer to talk to the host Docker daemon
      - /var/run/docker.sock:/var/run/docker.sock
