name: build_test

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - '*'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build and test with devcontainer
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer-ci/devcontainer.json
          runCmd: |
            just install && \
            just lint && \
            just test
